/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTradesRouteImport } from './routes/app.trades'
import { Route as AppSubscriptionRouteImport } from './routes/app.subscription'
import { Route as AppPortfolioRouteImport } from './routes/app.portfolio'
import { Route as AppPerformanceRouteImport } from './routes/app.performance'
import { Route as AppNotesRouteImport } from './routes/app.notes'
import { Route as AppMarketRouteImport } from './routes/app.market'
import { Route as AppLearningRouteImport } from './routes/app.learning'
import { Route as AppAnalyzeRouteImport } from './routes/app.analyze'
import { Route as AppAccountRouteImport } from './routes/app.account'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTradesRoute = AppTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketRoute = AppMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AppRoute,
} as any)
const AppLearningRoute = AppLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyzeRoute = AppAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/account': typeof AppAccountRoute
  '/app/analyze': typeof AppAnalyzeRoute
  '/app/learning': typeof AppLearningRoute
  '/app/market': typeof AppMarketRoute
  '/app/notes': typeof AppNotesRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/trades': typeof AppTradesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/account': typeof AppAccountRoute
  '/app/analyze': typeof AppAnalyzeRoute
  '/app/learning': typeof AppLearningRoute
  '/app/market': typeof AppMarketRoute
  '/app/notes': typeof AppNotesRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/trades': typeof AppTradesRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/account': typeof AppAccountRoute
  '/app/analyze': typeof AppAnalyzeRoute
  '/app/learning': typeof AppLearningRoute
  '/app/market': typeof AppMarketRoute
  '/app/notes': typeof AppNotesRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/trades': typeof AppTradesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/account'
    | '/app/analyze'
    | '/app/learning'
    | '/app/market'
    | '/app/notes'
    | '/app/performance'
    | '/app/portfolio'
    | '/app/subscription'
    | '/app/trades'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/account'
    | '/app/analyze'
    | '/app/learning'
    | '/app/market'
    | '/app/notes'
    | '/app/performance'
    | '/app/portfolio'
    | '/app/subscription'
    | '/app/trades'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/account'
    | '/app/analyze'
    | '/app/learning'
    | '/app/market'
    | '/app/notes'
    | '/app/performance'
    | '/app/portfolio'
    | '/app/subscription'
    | '/app/trades'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trades': {
      id: '/app/trades'
      path: '/trades'
      fullPath: '/app/trades'
      preLoaderRoute: typeof AppTradesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscription': {
      id: '/app/subscription'
      path: '/subscription'
      fullPath: '/app/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portfolio': {
      id: '/app/portfolio'
      path: '/portfolio'
      fullPath: '/app/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/performance': {
      id: '/app/performance'
      path: '/performance'
      fullPath: '/app/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes': {
      id: '/app/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/market': {
      id: '/app/market'
      path: '/market'
      fullPath: '/app/market'
      preLoaderRoute: typeof AppMarketRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/learning': {
      id: '/app/learning'
      path: '/learning'
      fullPath: '/app/learning'
      preLoaderRoute: typeof AppLearningRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analyze': {
      id: '/app/analyze'
      path: '/analyze'
      fullPath: '/app/analyze'
      preLoaderRoute: typeof AppAnalyzeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAnalyzeRoute: typeof AppAnalyzeRoute
  AppLearningRoute: typeof AppLearningRoute
  AppMarketRoute: typeof AppMarketRoute
  AppNotesRoute: typeof AppNotesRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppTradesRoute: typeof AppTradesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAnalyzeRoute: AppAnalyzeRoute,
  AppLearningRoute: AppLearningRoute,
  AppMarketRoute: AppMarketRoute,
  AppNotesRoute: AppNotesRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppTradesRoute: AppTradesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
